### ISSUE TITLE
Allow users to set custom flake path

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [DevPalace/phoenix-ci#14]
Currently, phoenix-ci assumes that `flake.nix` is in the root directory and there is no standard way to overwrite it. Property `flake` should be added which may accept a path or flake URI (We might be able to save a second or so if we were to use flake URI for this)

Sidenote:
I am not sure how flake URI would work in terms of `worker` action, probably would need to pass a ref from discovery in some cases :thinking:

**Comment by blaggacao** [comment]
> We might be able to save a second or so if we were to use flake URI for thi

Yes the checkout action is indeed roughly 1-2 seconds, but it also has a wall of verbose logs.

This is definitely a good idea!
