### ISSUE TITLE
Repro loophole on dirty checkout

### ISSUE THREAD

**Issue by blaggacao** [DevPalace/phoenix-ci#7]
https://github.com/DevPalace/phoenix-ci/blob/54915c42c63921ab95849dbc8c2d751015f7a733/src/nix.ts#L10

A checkout can be made dirty for example by an unfortunate previous action.

The user would not immediately note the misconfiguration and could (unknowingly) depend on an erroneous fallback constant for `self.rev`.

One way this can impact the stability of a system:
If `self.rev` is used as OCI image tag, inadvertently replacing unique tags by a constant can cause schedulers not to pull new versions (because the tag does not change).

A better strategy could be to always consume the remote flake which translate into a clean/fresh checkout.

Example upstream:

https://github.com/divnix/std-action/blob/5ead0a37047d44137f950247ee4d3e26fda291d7/discover/_eval.sh#L48-L51

**Comment by gytis-ivaskevicius** [comment]
`self.rev` does not default to `dirty` if I recall correctly, and almost all CI's have this issue. I'd say it's more of a user's fault if this happens

May be resolved by https://github.com/DevPalace/phoenix-ci/issues/13, but most likely will be resolved by https://github.com/DevPalace/phoenix-ci/issues/14

**Comment by blaggacao** [comment]
> self.rev does not default to dirty if I recall correctly,

Scenario:
- user work depends on `self.rev`
- user wants to exercise local workflow (potentially dirty)
- to unblock, [user defaults to a contsant](https://github.com/input-output-hk/hydra/pull/873/files#diff-206b9ce276ab5971a2489d75eb1b12999d4bf3843b7988cbe8d687cfde61dea0)

This is relatively common and this issue aims at preventing user error that can be quite annoying and impactful, by making it impossible without extra effort to hit this error scenario.

Maybe another way to address this would be `--no-allow-dirty` config for CI. That would allow the CI operator to switch on that safety measure to avoid the regular CI user make that mistake.

**Comment by gytis-ivaskevicius** [comment]
I don't think that's a real issue, either way its going to get resolved by #14

**Comment by gytis-ivaskevicius** [comment]
Resolved by https://github.com/DevPalace/phoenix-ci/issues/14
